#
# This is run with the current directory being
# ${CMAKE_CURRENT_BINARY_DIR}/postgres
#

rm -f ../libmaxscalepg.a

ar rcs ../libmaxscalepg.a \
./src/bin/initdb/findtimezone.o \
./src/bin/initdb/localtime.o \
./src/bin/initdb/initdb.o \
./src/common/logging.o \
./src/fe_utils/mbprint.o \
./src/fe_utils/query_utils.o \
./src/fe_utils/connect_utils.o \
./src/fe_utils/psqlscan.o \
./src/fe_utils/conditional.o \
./src/fe_utils/recovery_gen.o \
./src/fe_utils/string_utils.o \
./src/fe_utils/parallel_slot.o \
./src/fe_utils/print.o \
./src/fe_utils/cancel.o \
./src/fe_utils/option_utils.o \
./src/fe_utils/simple_list.o \
./src/fe_utils/archive.o \
./src/port/bsearch_arg_srv.o \
./src/port/fls.o \
./src/port/path.o \
./src/port/qsort_arg.o \
./src/port/pgstrcasecmp.o \
./src/port/path_srv.o \
./src/port/pqsignal.o \
./src/port/pgstrsignal_shlib.o \
./src/port/pqsignal_srv.o \
./src/port/pg_crc32c_sse42_choose.o \
./src/port/pgmkdirp_shlib.o \
./src/port/tar_shlib.o \
./src/port/quotes_srv.o \
./src/port/pg_crc32c_sse42_choose_shlib.o \
./src/port/pg_bitutils.o \
./src/port/strlcat_shlib.o \
./src/port/pgsleep.o \
./src/port/noblock_srv.o \
./src/port/inet_net_ntop_shlib.o \
./src/port/noblock.o \
./src/port/pg_strong_random.o \
./src/port/snprintf_shlib.o \
./src/port/strerror_srv.o \
./src/port/pg_crc32c_sse42_choose_srv.o \
./src/port/thread_srv.o \
./src/port/pgsleep_srv.o \
./src/port/noblock_shlib.o \
./src/port/tar.o \
./src/port/pg_crc32c_sse42_shlib.o \
./src/port/pg_bitutils_shlib.o \
./src/port/pg_crc32c_sb8_shlib.o \
./src/port/strerror.o \
./src/port/pg_strong_random_srv.o \
./src/port/bsearch_arg_shlib.o \
./src/port/tar_srv.o \
./src/port/quotes_shlib.o \
./src/port/snprintf_srv.o \
./src/port/pgstrsignal.o \
./src/port/strlcat.o \
./src/port/strlcat_srv.o \
./src/port/inet_net_ntop.o \
./src/port/qsort_srv.o \
./src/port/strlcpy_srv.o \
./src/port/pg_bitutils_srv.o \
./src/port/qsort.o \
./src/port/getpeereid.o \
./src/port/pg_strong_random_shlib.o \
./src/port/chklocale.o \
./src/port/quotes.o \
./src/port/qsort_arg_shlib.o \
./src/port/pgstrcasecmp_srv.o \
./src/port/path_shlib.o \
./src/port/pgstrsignal_srv.o \
./src/port/thread_shlib.o \
./src/port/snprintf.o \
./src/port/pqsignal_shlib.o \
./src/port/pgcheckdir_srv.o \
./src/port/pgcheckdir_shlib.o \
./src/port/qsort_shlib.o \
./src/port/pg_crc32c_sse42.o \
./src/port/getpeereid_srv.o \
./src/port/thread.o \
./src/port/inet_net_ntop_srv.o \
./src/port/pg_crc32c_sb8_srv.o \
./src/port/strlcpy.o \
./src/port/pgmkdirp_srv.o \
./src/port/pg_crc32c_sse42_srv.o \
./src/port/chklocale_srv.o \
./src/port/strerror_shlib.o \
./src/port/pg_crc32c_sb8.o \
./src/port/pgmkdirp.o \
./src/port/getpeereid_shlib.o \
./src/port/qsort_arg_srv.o \
./src/port/chklocale_shlib.o \
./src/port/bsearch_arg.o \
./src/port/pgstrcasecmp_shlib.o \
./src/port/pgsleep_shlib.o \
./src/port/strlcpy_shlib.o \
./src/port/pgcheckdir.o \
./src/backend/backup/backup_manifest.o \
./src/backend/backup/basebackup.o \
./src/backend/backup/basebackup_copy.o \
./src/backend/backup/basebackup_gzip.o \
./src/backend/backup/basebackup_lz4.o \
./src/backend/backup/basebackup_server.o \
./src/backend/backup/basebackup_target.o \
./src/backend/backup/basebackup_progress.o \
./src/backend/backup/basebackup_throttle.o \
./src/backend/backup/basebackup_zstd.o \
./src/backend/backup/basebackup_sink.o \
./src/backend/bootstrap/bootparse.o \
./src/backend/bootstrap/bootstrap.o \
./src/backend/postmaster/pgarch.o \
./src/backend/postmaster/auxprocess.o \
./src/backend/postmaster/walwriter.o \
./src/backend/postmaster/autovacuum.o \
./src/backend/postmaster/interrupt.o \
./src/backend/postmaster/bgworker.o \
./src/backend/postmaster/bgwriter.o \
./src/backend/postmaster/checkpointer.o \
./src/backend/postmaster/startup.o \
./src/backend/postmaster/fork_process.o \
./src/backend/postmaster/postmaster.o \
./src/backend/postmaster/syslogger.o \
./src/backend/postmaster/shell_archive.o \
./src/backend/foreign/foreign.o \
./src/backend/executor/nodeBitmapOr.o \
./src/backend/executor/nodeGatherMerge.o \
./src/backend/executor/nodeSubqueryscan.o \
./src/backend/executor/nodeHash.o \
./src/backend/executor/execPartition.o \
./src/backend/executor/nodeSubplan.o \
./src/backend/executor/nodeIncrementalSort.o \
./src/backend/executor/nodeMemoize.o \
./src/backend/executor/nodeNestloop.o \
./src/backend/executor/nodeModifyTable.o \
./src/backend/executor/nodeGather.o \
./src/backend/executor/execCurrent.o \
./src/backend/executor/nodeFunctionscan.o \
./src/backend/executor/execExpr.o \
./src/backend/executor/execSRF.o \
./src/backend/executor/instrument.o \
./src/backend/executor/nodeValuesscan.o \
./src/backend/executor/functions.o \
./src/backend/executor/nodeMergejoin.o \
./src/backend/executor/nodeAppend.o \
./src/backend/executor/nodeSort.o \
./src/backend/executor/nodeSamplescan.o \
./src/backend/executor/execProcnode.o \
./src/backend/executor/nodeSetOp.o \
./src/backend/executor/nodeForeignscan.o \
./src/backend/executor/nodeTidrangescan.o \
./src/backend/executor/nodeCustom.o \
./src/backend/executor/execIndexing.o \
./src/backend/executor/nodeMergeAppend.o \
./src/backend/executor/nodeLimit.o \
./src/backend/executor/execAsync.o \
./src/backend/executor/execScan.o \
./src/backend/executor/nodeAgg.o \
./src/backend/executor/execReplication.o \
./src/backend/executor/execParallel.o \
./src/backend/executor/nodeBitmapHeapscan.o \
./src/backend/executor/nodeIndexonlyscan.o \
./src/backend/executor/nodeLockRows.o \
./src/backend/executor/tqueue.o \
./src/backend/executor/nodeSeqscan.o \
./src/backend/executor/nodeResult.o \
./src/backend/executor/tstoreReceiver.o \
./src/backend/executor/execUtils.o \
./src/backend/executor/nodeTableFuncscan.o \
./src/backend/executor/execTuples.o \
./src/backend/executor/nodeIndexscan.o \
./src/backend/executor/nodeHashjoin.o \
./src/backend/executor/nodeTidscan.o \
./src/backend/executor/nodeNamedtuplestorescan.o \
./src/backend/executor/nodeProjectSet.o \
./src/backend/executor/execExprInterp.o \
./src/backend/executor/nodeBitmapAnd.o \
./src/backend/executor/nodeRecursiveunion.o \
./src/backend/executor/nodeWorktablescan.o \
./src/backend/executor/spi.o \
./src/backend/executor/execGrouping.o \
./src/backend/executor/execJunk.o \
./src/backend/executor/execAmi.o \
./src/backend/executor/nodeCtescan.o \
./src/backend/executor/execMain.o \
./src/backend/executor/nodeWindowAgg.o \
./src/backend/executor/nodeUnique.o \
./src/backend/executor/nodeGroup.o \
./src/backend/executor/nodeMaterial.o \
./src/backend/executor/nodeBitmapIndexscan.o \
./src/backend/tcop/fastpath.o \
./src/backend/tcop/utility.o \
./src/backend/tcop/dest.o \
./src/backend/tcop/pquery.o \
./src/backend/tcop/postgres.o \
./src/backend/tcop/cmdtag.o \
./src/backend/catalog/pg_range.o \
./src/backend/catalog/catalog.o \
./src/backend/catalog/aclchk.o \
./src/backend/catalog/pg_cast.o \
./src/backend/catalog/namespace.o \
./src/backend/catalog/toasting.o \
./src/backend/catalog/pg_collation.o \
./src/backend/catalog/objectaddress.o \
./src/backend/catalog/dependency.o \
./src/backend/catalog/pg_largeobject.o \
./src/backend/catalog/pg_conversion.o \
./src/backend/catalog/pg_aggregate.o \
./src/backend/catalog/pg_namespace.o \
./src/backend/catalog/pg_db_role_setting.o \
./src/backend/catalog/heap.o \
./src/backend/catalog/pg_depend.o \
./src/backend/catalog/objectaccess.o \
./src/backend/catalog/partition.o \
./src/backend/catalog/pg_type.o \
./src/backend/catalog/pg_publication.o \
./src/backend/catalog/pg_operator.o \
./src/backend/catalog/pg_class.o \
./src/backend/catalog/pg_subscription.o \
./src/backend/catalog/storage.o \
./src/backend/catalog/pg_attrdef.o \
./src/backend/catalog/pg_shdepend.o \
./src/backend/catalog/pg_proc.o \
./src/backend/catalog/indexing.o \
./src/backend/catalog/pg_constraint.o \
./src/backend/catalog/pg_enum.o \
./src/backend/catalog/pg_inherits.o \
./src/backend/catalog/pg_parameter_acl.o \
./src/backend/catalog/index.o \
./src/backend/tsearch/ts_parse.o \
./src/backend/tsearch/dict.o \
./src/backend/tsearch/to_tsany.o \
./src/backend/tsearch/ts_utils.o \
./src/backend/tsearch/ts_selfuncs.o \
./src/backend/tsearch/wparser_def.o \
./src/backend/tsearch/dict_simple.o \
./src/backend/tsearch/spell.o \
./src/backend/tsearch/ts_typanalyze.o \
./src/backend/tsearch/dict_synonym.o \
./src/backend/tsearch/dict_ispell.o \
./src/backend/tsearch/wparser.o \
./src/backend/tsearch/regis.o \
./src/backend/tsearch/dict_thesaurus.o \
./src/backend/tsearch/ts_locale.o \
./src/backend/rewrite/rewriteDefine.o \
./src/backend/rewrite/rewriteManip.o \
./src/backend/rewrite/rowsecurity.o \
./src/backend/rewrite/rewriteRemove.o \
./src/backend/rewrite/rewriteSupport.o \
./src/backend/rewrite/rewriteSearchCycle.o \
./src/backend/rewrite/rewriteHandler.o \
./src/backend/libpq/pqsignal.o \
./src/backend/libpq/hba.o \
./src/backend/libpq/pqformat.o \
./src/backend/libpq/auth.o \
./src/backend/libpq/ifaddr.o \
./src/backend/libpq/pqmq.o \
./src/backend/libpq/auth-sasl.o \
./src/backend/libpq/be-fsstubs.o \
./src/backend/libpq/pqcomm.o \
./src/backend/libpq/be-secure-common.o \
./src/backend/libpq/crypt.o \
./src/backend/libpq/auth-scram.o \
./src/backend/libpq/be-secure.o \
./src/backend/partitioning/partbounds.o \
./src/backend/partitioning/partprune.o \
./src/backend/partitioning/partdesc.o \
./src/backend/port/atomics.o \
./src/backend/port/pg_sema.o \
./src/backend/port/pg_shmem.o \
./src/backend/optimizer/plan/subselect.o \
./src/backend/optimizer/plan/setrefs.o \
./src/backend/optimizer/plan/createplan.o \
./src/backend/optimizer/plan/planmain.o \
./src/backend/optimizer/plan/initsplan.o \
./src/backend/optimizer/plan/analyzejoins.o \
./src/backend/optimizer/plan/planner.o \
./src/backend/optimizer/plan/planagg.o \
./src/backend/optimizer/util/joininfo.o \
./src/backend/optimizer/util/inherit.o \
./src/backend/optimizer/util/appendinfo.o \
./src/backend/optimizer/util/restrictinfo.o \
./src/backend/optimizer/util/orclauses.o \
./src/backend/optimizer/util/pathnode.o \
./src/backend/optimizer/util/clauses.o \
./src/backend/optimizer/util/tlist.o \
./src/backend/optimizer/util/predtest.o \
./src/backend/optimizer/util/relnode.o \
./src/backend/optimizer/util/plancat.o \
./src/backend/optimizer/util/placeholder.o \
./src/backend/optimizer/util/paramassign.o \
./src/backend/optimizer/util/var.o \
./src/backend/optimizer/geqo/geqo_main.o \
./src/backend/optimizer/geqo/geqo_eval.o \
./src/backend/optimizer/geqo/geqo_copy.o \
./src/backend/optimizer/geqo/geqo_pool.o \
./src/backend/optimizer/geqo/geqo_erx.o \
./src/backend/optimizer/geqo/geqo_selection.o \
./src/backend/optimizer/geqo/geqo_misc.o \
./src/backend/optimizer/geqo/geqo_random.o \
./src/backend/optimizer/geqo/geqo_recombination.o \
./src/backend/optimizer/geqo/geqo_cx.o \
./src/backend/optimizer/geqo/geqo_ox1.o \
./src/backend/optimizer/geqo/geqo_pmx.o \
./src/backend/optimizer/geqo/geqo_ox2.o \
./src/backend/optimizer/geqo/geqo_px.o \
./src/backend/optimizer/geqo/geqo_mutation.o \
./src/backend/optimizer/prep/prepagg.o \
./src/backend/optimizer/prep/prepjointree.o \
./src/backend/optimizer/prep/prepunion.o \
./src/backend/optimizer/prep/preptlist.o \
./src/backend/optimizer/prep/prepqual.o \
./src/backend/optimizer/path/clausesel.o \
./src/backend/optimizer/path/joinpath.o \
./src/backend/optimizer/path/equivclass.o \
./src/backend/optimizer/path/tidpath.o \
./src/backend/optimizer/path/joinrels.o \
./src/backend/optimizer/path/indxpath.o \
./src/backend/optimizer/path/costsize.o \
./src/backend/optimizer/path/allpaths.o \
./src/backend/optimizer/path/pathkeys.o \
./src/backend/nodes/readfuncs.o \
./src/backend/nodes/bitmapset.o \
./src/backend/nodes/equalfuncs.o \
./src/backend/nodes/print.o \
./src/backend/nodes/list.o \
./src/backend/nodes/tidbitmap.o \
./src/backend/nodes/params.o \
./src/backend/nodes/copyfuncs.o \
./src/backend/nodes/makefuncs.o \
./src/backend/nodes/extensible.o \
./src/backend/nodes/outfuncs.o \
./src/backend/nodes/nodeFuncs.o \
./src/backend/nodes/nodes.o \
./src/backend/nodes/read.o \
./src/backend/nodes/value.o \
./src/backend/replication/repl_gram.o \
./src/backend/replication/walsender.o \
./src/backend/replication/syncrep_gram.o \
./src/backend/replication/slot.o \
./src/backend/replication/walreceiver.o \
./src/backend/replication/pgoutput/pgoutput.o \
./src/backend/replication/logical/decode.o \
./src/backend/replication/logical/logicalfuncs.o \
./src/backend/replication/logical/message.o \
./src/backend/replication/logical/logical.o \
./src/backend/replication/logical/relation.o \
./src/backend/replication/logical/launcher.o \
./src/backend/replication/logical/reorderbuffer.o \
./src/backend/replication/logical/origin.o \
./src/backend/replication/logical/proto.o \
./src/backend/replication/logical/worker.o \
./src/backend/replication/logical/tablesync.o \
./src/backend/replication/logical/snapbuild.o \
./src/backend/replication/syncrep.o \
./src/backend/replication/walreceiverfuncs.o \
./src/backend/replication/libpqwalreceiver/libpqwalreceiver.o \
./src/backend/replication/slotfuncs.o \
./src/backend/access/nbtree/nbtsort.o \
./src/backend/access/nbtree/nbtree.o \
./src/backend/access/nbtree/nbtcompare.o \
./src/backend/access/nbtree/nbtutils.o \
./src/backend/access/nbtree/nbtdedup.o \
./src/backend/access/nbtree/nbtvalidate.o \
./src/backend/access/nbtree/nbtpage.o \
./src/backend/access/nbtree/nbtsplitloc.o \
./src/backend/access/nbtree/nbtsearch.o \
./src/backend/access/nbtree/nbtinsert.o \
./src/backend/access/nbtree/nbtxlog.o \
./src/backend/access/hash/hash_xlog.o \
./src/backend/access/hash/hashsearch.o \
./src/backend/access/hash/hashinsert.o \
./src/backend/access/hash/hashvalidate.o \
./src/backend/access/hash/hashfunc.o \
./src/backend/access/hash/hashovfl.o \
./src/backend/access/hash/hashutil.o \
./src/backend/access/hash/hashpage.o \
./src/backend/access/hash/hash.o \
./src/backend/access/hash/hashsort.o \
./src/backend/access/table/tableamapi.o \
./src/backend/access/table/tableam.o \
./src/backend/access/table/table.o \
./src/backend/access/table/toast_helper.o \
./src/backend/access/common/session.o \
./src/backend/access/common/printtup.o \
./src/backend/access/common/reloptions.o \
./src/backend/access/common/relation.o \
./src/backend/access/common/toast_compression.o \
./src/backend/access/common/tupconvert.o \
./src/backend/access/common/indextuple.o \
./src/backend/access/common/toast_internals.o \
./src/backend/access/common/attmap.o \
./src/backend/access/common/tupdesc.o \
./src/backend/access/common/bufmask.o \
./src/backend/access/common/syncscan.o \
./src/backend/access/common/scankey.o \
./src/backend/access/common/detoast.o \
./src/backend/access/common/printsimple.o \
./src/backend/access/common/heaptuple.o \
./src/backend/access/transam/rmgr.o \
./src/backend/access/transam/xlog.o \
./src/backend/access/transam/xlogfuncs.o \
./src/backend/access/transam/xlogutils.o \
./src/backend/access/transam/slru.o \
./src/backend/access/transam/xlogreader.o \
./src/backend/access/transam/twophase.o \
./src/backend/access/transam/xloginsert.o \
./src/backend/access/transam/xlogstats.o \
./src/backend/access/transam/twophase_rmgr.o \
./src/backend/access/transam/generic_xlog.o \
./src/backend/access/transam/xact.o \
./src/backend/access/transam/multixact.o \
./src/backend/access/transam/parallel.o \
./src/backend/access/transam/subtrans.o \
./src/backend/access/transam/clog.o \
./src/backend/access/transam/commit_ts.o \
./src/backend/access/transam/xlogarchive.o \
./src/backend/access/transam/xlogrecovery.o \
./src/backend/access/transam/transam.o \
./src/backend/access/transam/xlogprefetcher.o \
./src/backend/access/transam/timeline.o \
./src/backend/access/transam/varsup.o \
./src/backend/access/brin/brin_pageops.o \
./src/backend/access/brin/brin_revmap.o \
./src/backend/access/brin/brin.o \
./src/backend/access/brin/brin_xlog.o \
./src/backend/access/brin/brin_minmax.o \
./src/backend/access/brin/brin_tuple.o \
./src/backend/access/brin/brin_minmax_multi.o \
./src/backend/access/brin/brin_inclusion.o \
./src/backend/access/brin/brin_bloom.o \
./src/backend/access/brin/brin_validate.o \
./src/backend/access/heap/heapam_handler.o \
./src/backend/access/heap/hio.o \
./src/backend/access/heap/heaptoast.o \
./src/backend/access/heap/vacuumlazy.o \
./src/backend/access/heap/rewriteheap.o \
./src/backend/access/heap/visibilitymap.o \
./src/backend/access/heap/heapam_visibility.o \
./src/backend/access/heap/heapam.o \
./src/backend/access/heap/pruneheap.o \
./src/backend/access/tablesample/bernoulli.o \
./src/backend/access/tablesample/tablesample.o \
./src/backend/access/tablesample/system.o \
./src/backend/access/gin/ginarrayproc.o \
./src/backend/access/gin/ginutil.o \
./src/backend/access/gin/ginget.o \
./src/backend/access/gin/ginscan.o \
./src/backend/access/gin/gindatapage.o \
./src/backend/access/gin/gininsert.o \
./src/backend/access/gin/ginvalidate.o \
./src/backend/access/gin/ginxlog.o \
./src/backend/access/gin/ginpostinglist.o \
./src/backend/access/gin/ginlogic.o \
./src/backend/access/gin/ginentrypage.o \
./src/backend/access/gin/ginfast.o \
./src/backend/access/gin/ginbulk.o \
./src/backend/access/gin/ginvacuum.o \
./src/backend/access/gin/ginbtree.o \
./src/backend/access/spgist/spgkdtreeproc.o \
./src/backend/access/spgist/spgutils.o \
./src/backend/access/spgist/spgtextproc.o \
./src/backend/access/spgist/spgxlog.o \
./src/backend/access/spgist/spginsert.o \
./src/backend/access/spgist/spgdoinsert.o \
./src/backend/access/spgist/spgproc.o \
./src/backend/access/spgist/spgvalidate.o \
./src/backend/access/spgist/spgvacuum.o \
./src/backend/access/spgist/spgscan.o \
./src/backend/access/spgist/spgquadtreeproc.o \
./src/backend/access/rmgrdesc/clogdesc.o \
./src/backend/access/rmgrdesc/xlogdesc.o \
./src/backend/access/rmgrdesc/committsdesc.o \
./src/backend/access/rmgrdesc/brindesc.o \
./src/backend/access/rmgrdesc/tblspcdesc.o \
./src/backend/access/rmgrdesc/genericdesc.o \
./src/backend/access/rmgrdesc/nbtdesc.o \
./src/backend/access/rmgrdesc/hashdesc.o \
./src/backend/access/rmgrdesc/relmapdesc.o \
./src/backend/access/rmgrdesc/replorigindesc.o \
./src/backend/access/rmgrdesc/seqdesc.o \
./src/backend/access/rmgrdesc/spgdesc.o \
./src/backend/access/rmgrdesc/dbasedesc.o \
./src/backend/access/rmgrdesc/mxactdesc.o \
./src/backend/access/rmgrdesc/xactdesc.o \
./src/backend/access/rmgrdesc/smgrdesc.o \
./src/backend/access/rmgrdesc/gindesc.o \
./src/backend/access/rmgrdesc/standbydesc.o \
./src/backend/access/rmgrdesc/gistdesc.o \
./src/backend/access/rmgrdesc/heapdesc.o \
./src/backend/access/rmgrdesc/logicalmsgdesc.o \
./src/backend/access/gist/gist.o \
./src/backend/access/gist/gistutil.o \
./src/backend/access/gist/gistbuild.o \
./src/backend/access/gist/gistxlog.o \
./src/backend/access/gist/gistproc.o \
./src/backend/access/gist/gistget.o \
./src/backend/access/gist/gistscan.o \
./src/backend/access/gist/gistsplit.o \
./src/backend/access/gist/gistvalidate.o \
./src/backend/access/gist/gistbuildbuffers.o \
./src/backend/access/gist/gistvacuum.o \
./src/backend/access/index/indexam.o \
./src/backend/access/index/amapi.o \
./src/backend/access/index/amvalidate.o \
./src/backend/access/index/genam.o \
./src/backend/storage/lmgr/s_lock.o \
./src/backend/storage/lmgr/deadlock.o \
./src/backend/storage/lmgr/lwlock.o \
./src/backend/storage/lmgr/lmgr.o \
./src/backend/storage/lmgr/lwlocknames.o \
./src/backend/storage/lmgr/spin.o \
./src/backend/storage/lmgr/predicate.o \
./src/backend/storage/lmgr/condition_variable.o \
./src/backend/storage/lmgr/lock.o \
./src/backend/storage/lmgr/proc.o \
./src/backend/storage/smgr/md.o \
./src/backend/storage/smgr/smgr.o \
./src/backend/storage/freespace/freespace.o \
./src/backend/storage/freespace/fsmpage.o \
./src/backend/storage/freespace/indexfsm.o \
./src/backend/storage/large_object/inv_api.o \
./src/backend/storage/ipc/barrier.o \
./src/backend/storage/ipc/dsm_impl.o \
./src/backend/storage/ipc/dsm.o \
./src/backend/storage/ipc/ipci.o \
./src/backend/storage/ipc/ipc.o \
./src/backend/storage/ipc/latch.o \
./src/backend/storage/ipc/pmsignal.o \
./src/backend/storage/ipc/procarray.o \
./src/backend/storage/ipc/procsignal.o \
./src/backend/storage/ipc/shmem.o \
./src/backend/storage/ipc/shm_mq.o \
./src/backend/storage/ipc/shmqueue.o \
./src/backend/storage/ipc/shm_toc.o \
./src/backend/storage/ipc/signalfuncs.o \
./src/backend/storage/ipc/sinval.o \
./src/backend/storage/ipc/sinvaladt.o \
./src/backend/storage/ipc/standby.o \
./src/backend/storage/buffer/bufmgr.o \
./src/backend/storage/buffer/buf_table.o \
./src/backend/storage/buffer/buf_init.o \
./src/backend/storage/buffer/localbuf.o \
./src/backend/storage/buffer/freelist.o \
./src/backend/storage/file/buffile.o \
./src/backend/storage/file/sharedfileset.o \
./src/backend/storage/file/copydir.o \
./src/backend/storage/file/reinit.o \
./src/backend/storage/file/fileset.o \
./src/backend/storage/file/fd.o \
./src/backend/storage/page/itemptr.o \
./src/backend/storage/page/bufpage.o \
./src/backend/storage/page/checksum.o \
./src/backend/storage/sync/sync.o \
./src/backend/commands/collationcmds.o \
./src/backend/commands/async.o \
./src/backend/commands/foreigncmds.o \
./src/backend/commands/tablecmds.o \
./src/backend/commands/user.o \
./src/backend/commands/comment.o \
./src/backend/commands/opclasscmds.o \
./src/backend/commands/extension.o \
./src/backend/commands/dbcommands.o \
./src/backend/commands/proclang.o \
./src/backend/commands/createas.o \
./src/backend/commands/matview.o \
./src/backend/commands/tsearchcmds.o \
./src/backend/commands/operatorcmds.o \
./src/backend/commands/dropcmds.o \
./src/backend/commands/conversioncmds.o \
./src/backend/commands/event_trigger.o \
./src/backend/commands/typecmds.o \
./src/backend/commands/copyfrom.o \
./src/backend/commands/explain.o \
./src/backend/commands/indexcmds.o \
./src/backend/commands/variable.o \
./src/backend/commands/vacuumparallel.o \
./src/backend/commands/copyto.o \
./src/backend/commands/discard.o \
./src/backend/commands/aggregatecmds.o \
./src/backend/commands/cluster.o \
./src/backend/commands/schemacmds.o \
./src/backend/commands/vacuum.o \
./src/backend/commands/define.o \
./src/backend/commands/constraint.o \
./src/backend/commands/policy.o \
./src/backend/commands/lockcmds.o \
./src/backend/commands/statscmds.o \
./src/backend/commands/tablespace.o \
./src/backend/commands/analyze.o \
./src/backend/commands/trigger.o \
./src/backend/commands/alter.o \
./src/backend/commands/functioncmds.o \
./src/backend/commands/view.o \
./src/backend/commands/amcmds.o \
./src/backend/commands/portalcmds.o \
./src/backend/commands/copy.o \
./src/backend/commands/publicationcmds.o \
./src/backend/commands/subscriptioncmds.o \
./src/backend/commands/prepare.o \
./src/backend/commands/copyfromparse.o \
./src/backend/commands/sequence.o \
./src/backend/commands/seclabel.o \
./src/backend/regex/regcomp.o \
./src/backend/regex/regexport.o \
./src/backend/regex/regexec.o \
./src/backend/regex/regfree.o \
./src/backend/regex/regprefix.o \
./src/backend/regex/regerror.o \
./src/backend/statistics/mvdistinct.o \
./src/backend/statistics/dependencies.o \
./src/backend/statistics/mcv.o \
./src/backend/statistics/extended_stats.o \
./src/backend/parser/scan.o \
./src/backend/parser/parse_node.o \
./src/backend/parser/parse_agg.o \
./src/backend/parser/parse_type.o \
./src/backend/parser/parse_target.o \
./src/backend/parser/parse_cte.o \
./src/backend/parser/parse_clause.o \
./src/backend/parser/scansup.o \
./src/backend/parser/gram.o \
./src/backend/parser/parse_coerce.o \
./src/backend/parser/parse_expr.o \
./src/backend/parser/parse_utilcmd.o \
./src/backend/parser/parse_relation.o \
./src/backend/parser/parse_param.o \
./src/backend/parser/analyze.o \
./src/backend/parser/parse_func.o \
./src/backend/parser/parser.o \
./src/backend/parser/parse_enr.o \
./src/backend/parser/parse_merge.o \
./src/backend/parser/parse_collate.o \
./src/backend/parser/parse_oper.o \
./src/backend/snowball/stem_UTF_8_irish.o \
./src/backend/snowball/stem_ISO_8859_1_english.o \
./src/backend/snowball/stem_UTF_8_portuguese.o \
./src/backend/snowball/stem_UTF_8_catalan.o \
./src/backend/snowball/stem_UTF_8_norwegian.o \
./src/backend/snowball/stem_UTF_8_nepali.o \
./src/backend/snowball/stem_ISO_8859_1_porter.o \
./src/backend/snowball/stem_ISO_8859_1_italian.o \
./src/backend/snowball/stem_ISO_8859_2_hungarian.o \
./src/backend/snowball/dict_snowball.o \
./src/backend/snowball/stem_UTF_8_lithuanian.o \
./src/backend/snowball/stem_UTF_8_finnish.o \
./src/backend/snowball/stem_UTF_8_porter.o \
./src/backend/snowball/stem_UTF_8_armenian.o \
./src/backend/snowball/stem_ISO_8859_1_finnish.o \
./src/backend/snowball/stem_KOI8_R_russian.o \
./src/backend/snowball/stem_UTF_8_dutch.o \
./src/backend/snowball/stem_UTF_8_french.o \
./src/backend/snowball/stem_ISO_8859_1_german.o \
./src/backend/snowball/stem_UTF_8_arabic.o \
./src/backend/snowball/stem_ISO_8859_1_indonesian.o \
./src/backend/snowball/stem_ISO_8859_1_catalan.o \
./src/backend/snowball/stem_UTF_8_indonesian.o \
./src/backend/snowball/stem_UTF_8_english.o \
./src/backend/snowball/stem_UTF_8_greek.o \
./src/backend/snowball/stem_ISO_8859_2_romanian.o \
./src/backend/snowball/stem_ISO_8859_1_french.o \
./src/backend/snowball/stem_UTF_8_turkish.o \
./src/backend/snowball/stem_UTF_8_hungarian.o \
./src/backend/snowball/stem_ISO_8859_1_irish.o \
./src/backend/snowball/stem_UTF_8_serbian.o \
./src/backend/snowball/utilities.o \
./src/backend/snowball/stem_UTF_8_romanian.o \
./src/backend/snowball/stem_UTF_8_german.o \
./src/backend/snowball/stem_UTF_8_russian.o \
./src/backend/snowball/stem_ISO_8859_1_norwegian.o \
./src/backend/snowball/stem_UTF_8_yiddish.o \
./src/backend/snowball/stem_ISO_8859_1_portuguese.o \
./src/backend/snowball/stem_ISO_8859_1_spanish.o \
./src/backend/snowball/stem_UTF_8_swedish.o \
./src/backend/snowball/stem_UTF_8_spanish.o \
./src/backend/snowball/stem_UTF_8_hindi.o \
./src/backend/snowball/stem_ISO_8859_1_swedish.o \
./src/backend/snowball/stem_UTF_8_danish.o \
./src/backend/snowball/api.o \
./src/backend/snowball/stem_ISO_8859_1_basque.o \
./src/backend/snowball/stem_ISO_8859_1_dutch.o \
./src/backend/snowball/stem_ISO_8859_1_danish.o \
./src/backend/snowball/stem_UTF_8_tamil.o \
./src/backend/snowball/stem_UTF_8_italian.o \
./src/backend/snowball/stem_UTF_8_basque.o \
./src/backend/utils/fmgr/fmgr.o \
./src/backend/utils/fmgr/dfmgr.o \
./src/backend/utils/fmgr/funcapi.o \
./src/backend/utils/hash/pg_crc.o \
./src/backend/utils/hash/dynahash.o \
./src/backend/utils/fmgrtab.o \
./src/backend/utils/activity/wait_event.o \
./src/backend/utils/activity/pgstat_slru.o \
./src/backend/utils/activity/pgstat_xact.o \
./src/backend/utils/activity/backend_progress.o \
./src/backend/utils/activity/pgstat_subscription.o \
./src/backend/utils/activity/pgstat_archiver.o \
./src/backend/utils/activity/pgstat_checkpointer.o \
./src/backend/utils/activity/pgstat_relation.o \
./src/backend/utils/activity/pgstat_bgwriter.o \
./src/backend/utils/activity/backend_status.o \
./src/backend/utils/activity/pgstat_wal.o \
./src/backend/utils/activity/pgstat_database.o \
./src/backend/utils/activity/pgstat_replslot.o \
./src/backend/utils/activity/pgstat_function.o \
./src/backend/utils/activity/pgstat.o \
./src/backend/utils/activity/pgstat_shmem.o \
./src/backend/utils/resowner/resowner.o \
./src/backend/utils/sort/tuplesort.o \
./src/backend/utils/sort/qsort_interruptible.o \
./src/backend/utils/sort/logtape.o \
./src/backend/utils/sort/tuplestore.o \
./src/backend/utils/sort/sharedtuplestore.o \
./src/backend/utils/sort/sortsupport.o \
./src/backend/utils/init/globals.o \
./src/backend/utils/init/miscinit.o \
./src/backend/utils/init/postinit.o \
./src/backend/utils/error/elog.o \
./src/backend/utils/error/assert.o \
./src/backend/utils/error/csvlog.o \
./src/backend/utils/error/jsonlog.o \
./src/backend/utils/misc/pg_rusage.o \
./src/backend/utils/misc/pg_config.o \
./src/backend/utils/misc/superuser.o \
./src/backend/utils/misc/ps_status.o \
./src/backend/utils/misc/queryenvironment.o \
./src/backend/utils/misc/queryjumble.o \
./src/backend/utils/misc/guc.o \
./src/backend/utils/misc/pg_controldata.o \
./src/backend/utils/misc/rls.o \
./src/backend/utils/misc/help_config.o \
./src/backend/utils/misc/sampling.o \
./src/backend/utils/misc/timeout.o \
./src/backend/utils/misc/tzparser.o \
./src/backend/utils/time/combocid.o \
./src/backend/utils/time/snapmgr.o \
./src/backend/utils/adt/cash.o \
./src/backend/utils/adt/pg_locale.o \
./src/backend/utils/adt/tsvector.o \
./src/backend/utils/adt/format_type.o \
./src/backend/utils/adt/mac.o \
./src/backend/utils/adt/geo_selfuncs.o \
./src/backend/utils/adt/network_selfuncs.o \
./src/backend/utils/adt/mcxtfuncs.o \
./src/backend/utils/adt/network_gist.o \
./src/backend/utils/adt/uuid.o \
./src/backend/utils/adt/array_userfuncs.o \
./src/backend/utils/adt/char.o \
./src/backend/utils/adt/cryptohashfuncs.o \
./src/backend/utils/adt/multirangetypes.o \
./src/backend/utils/adt/geo_spgist.o \
./src/backend/utils/adt/tsginidx.o \
./src/backend/utils/adt/domains.o \
./src/backend/utils/adt/arraysubs.o \
./src/backend/utils/adt/oracle_compat.o \
./src/backend/utils/adt/trigfuncs.o \
./src/backend/utils/adt/network_spgist.o \
./src/backend/utils/adt/tsvector_op.o \
./src/backend/utils/adt/xid8funcs.o \
./src/backend/utils/adt/jsonb_util.o \
./src/backend/utils/adt/rangetypes_spgist.o \
./src/backend/utils/adt/ruleutils.o \
./src/backend/utils/adt/pgstatfuncs.o \
./src/backend/utils/adt/tsquery.o \
./src/backend/utils/adt/array_typanalyze.o \
./src/backend/utils/adt/tid.o \
./src/backend/utils/adt/orderedsetaggs.o \
./src/backend/utils/adt/pg_upgrade_support.o \
./src/backend/utils/adt/datetime.o \
./src/backend/utils/adt/enum.o \
./src/backend/utils/adt/jsonbsubs.o \
./src/backend/utils/adt/pseudotypes.o \
./src/backend/utils/adt/genfile.o \
./src/backend/utils/adt/int8.o \
./src/backend/utils/adt/varbit.o \
./src/backend/utils/adt/jsonpath.o \
./src/backend/utils/adt/quote.o \
./src/backend/utils/adt/geo_ops.o \
./src/backend/utils/adt/rowtypes.o \
./src/backend/utils/adt/tsquery_op.o \
./src/backend/utils/adt/multirangetypes_selfuncs.o \
./src/backend/utils/adt/network.o \
./src/backend/utils/adt/numeric.o \
./src/backend/utils/adt/pg_lsn.o \
./src/backend/utils/adt/rangetypes_typanalyze.o \
./src/backend/utils/adt/ascii.o \
./src/backend/utils/adt/misc.o \
./src/backend/utils/adt/windowfuncs.o \
./src/backend/utils/adt/version.o \
./src/backend/utils/adt/varchar.o \
./src/backend/utils/adt/array_expanded.o \
./src/backend/utils/adt/xid.o \
./src/backend/utils/adt/regproc.o \
./src/backend/utils/adt/tsrank.o \
./src/backend/utils/adt/varlena.o \
./src/backend/utils/adt/acl.o \
./src/backend/utils/adt/rangetypes_gist.o \
./src/backend/utils/adt/jsonpath_gram.o \
./src/backend/utils/adt/tsquery_util.o \
./src/backend/utils/adt/jsonb_op.o \
./src/backend/utils/adt/datum.o \
./src/backend/utils/adt/numutils.o \
./src/backend/utils/adt/ri_triggers.o \
./src/backend/utils/adt/amutils.o \
./src/backend/utils/adt/jsonb_gin.o \
./src/backend/utils/adt/tsquery_gist.o \
./src/backend/utils/adt/arrayutils.o \
./src/backend/utils/adt/selfuncs.o \
./src/backend/utils/adt/tsgistidx.o \
./src/backend/utils/adt/timestamp.o \
./src/backend/utils/adt/encode.o \
./src/backend/utils/adt/lockfuncs.o \
./src/backend/utils/adt/tsvector_parser.o \
./src/backend/utils/adt/rangetypes.o \
./src/backend/utils/adt/inet_cidr_ntop.o \
./src/backend/utils/adt/name.o \
./src/backend/utils/adt/bool.o \
./src/backend/utils/adt/like_support.o \
./src/backend/utils/adt/expandeddatum.o \
./src/backend/utils/adt/mac8.o \
./src/backend/utils/adt/jsonpath_exec.o \
./src/backend/utils/adt/int.o \
./src/backend/utils/adt/formatting.o \
./src/backend/utils/adt/regexp.o \
./src/backend/utils/adt/expandedrecord.o \
./src/backend/utils/adt/tsquery_rewrite.o \
./src/backend/utils/adt/rangetypes_selfuncs.o \
./src/backend/utils/adt/jsonb.o \
./src/backend/utils/adt/dbsize.o \
./src/backend/utils/adt/like.o \
./src/backend/utils/adt/array_selfuncs.o \
./src/backend/utils/adt/float.o \
./src/backend/utils/adt/oid.o \
./src/backend/utils/adt/date.o \
./src/backend/utils/adt/hbafuncs.o \
./src/backend/utils/adt/partitionfuncs.o \
./src/backend/utils/adt/tsquery_cleanup.o \
./src/backend/utils/adt/json.o \
./src/backend/utils/adt/xml.o \
./src/backend/utils/adt/arrayfuncs.o \
./src/backend/utils/adt/jsonfuncs.o \
./src/backend/utils/adt/inet_net_pton.o \
./src/backend/utils/mmgr/slab.o \
./src/backend/utils/mmgr/portalmem.o \
./src/backend/utils/mmgr/memdebug.o \
./src/backend/utils/mmgr/dsa.o \
./src/backend/utils/mmgr/mcxt.o \
./src/backend/utils/mmgr/aset.o \
./src/backend/utils/mmgr/generation.o \
./src/backend/utils/mmgr/freepage.o \
./src/backend/utils/cache/attoptcache.o \
./src/backend/utils/cache/relmapper.o \
./src/backend/utils/cache/lsyscache.o \
./src/backend/utils/cache/typcache.o \
./src/backend/utils/cache/catcache.o \
./src/backend/utils/cache/relcache.o \
./src/backend/utils/cache/ts_cache.o \
./src/backend/utils/cache/plancache.o \
./src/backend/utils/cache/partcache.o \
./src/backend/utils/cache/relfilenodemap.o \
./src/backend/utils/cache/syscache.o \
./src/backend/utils/cache/inval.o \
./src/backend/utils/cache/evtcache.o \
./src/backend/utils/cache/spccache.o \
./src/backend/utils/mb/stringinfo_mb.o \
./src/backend/utils/mb/wstrcmp.o \
./src/backend/utils/mb/wstrncmp.o \
./src/backend/utils/mb/conversion_procs/euc_jp_and_sjis/euc_jp_and_sjis.o \
./src/backend/utils/mb/conversion_procs/utf8_and_iso8859/utf8_and_iso8859.o \
./src/backend/utils/mb/conversion_procs/utf8_and_gbk/utf8_and_gbk.o \
./src/backend/utils/mb/conversion_procs/utf8_and_win/utf8_and_win.o \
./src/backend/utils/mb/conversion_procs/utf8_and_gb18030/utf8_and_gb18030.o \
./src/backend/utils/mb/conversion_procs/utf8_and_sjis2004/utf8_and_sjis2004.o \
./src/backend/utils/mb/conversion_procs/utf8_and_iso8859_1/utf8_and_iso8859_1.o \
./src/backend/utils/mb/conversion_procs/euc_cn_and_mic/euc_cn_and_mic.o \
./src/backend/utils/mb/conversion_procs/latin2_and_win1250/latin2_and_win1250.o \
./src/backend/utils/mb/conversion_procs/utf8_and_euc_jp/utf8_and_euc_jp.o \
./src/backend/utils/mb/conversion_procs/euc_tw_and_big5/euc_tw_and_big5.o \
./src/backend/utils/mb/conversion_procs/euc_tw_and_big5/big5.o \
./src/backend/utils/mb/conversion_procs/latin_and_mic/latin_and_mic.o \
./src/backend/utils/mb/conversion_procs/utf8_and_big5/utf8_and_big5.o \
./src/backend/utils/mb/conversion_procs/utf8_and_euc_tw/utf8_and_euc_tw.o \
./src/backend/utils/mb/conversion_procs/utf8_and_euc_cn/utf8_and_euc_cn.o \
./src/backend/utils/mb/conversion_procs/utf8_and_cyrillic/utf8_and_cyrillic.o \
./src/backend/utils/mb/conversion_procs/euc_kr_and_mic/euc_kr_and_mic.o \
./src/backend/utils/mb/conversion_procs/utf8_and_johab/utf8_and_johab.o \
./src/backend/utils/mb/conversion_procs/utf8_and_uhc/utf8_and_uhc.o \
./src/backend/utils/mb/conversion_procs/utf8_and_euc2004/utf8_and_euc2004.o \
./src/backend/utils/mb/conversion_procs/utf8_and_euc_kr/utf8_and_euc_kr.o \
./src/backend/utils/mb/conversion_procs/cyrillic_and_mic/cyrillic_and_mic.o \
./src/backend/utils/mb/conversion_procs/utf8_and_sjis/utf8_and_sjis.o \
./src/backend/utils/mb/conversion_procs/euc2004_sjis2004/euc2004_sjis2004.o \
./src/backend/utils/mb/mbutils.o \
./src/backend/utils/mb/conv.o \
./src/backend/jit/jit.o \
./src/backend/lib/pairingheap.o \
./src/backend/lib/bipartite_match.o \
./src/backend/lib/ilist.o \
./src/backend/lib/knapsack.o \
./src/backend/lib/hyperloglog.o \
./src/backend/lib/bloomfilter.o \
./src/backend/lib/binaryheap.o \
./src/backend/lib/dshash.o \
./src/backend/lib/rbtree.o \
./src/backend/lib/integerset.o \
./src/timezone/zic.o \
./src/timezone/pgtz.o \
./src/timezone/localtime.o \
./src/timezone/strftime.o \
