#!/bin/bash

$test_dir/configure_maxscale.sh

mariadb_err=`mysql -u no_such_user -psome_pwd -h $repl_001 test 2>&1`
maxscale_err=`mysql -u no_such_user -psome_pwd -h $Maxscale_IP -P 4006 test 2>&1`

echo "MariaDB message"
echo "$mariadb_err"
echo " "
echo "Maxscale message"
echo "$maxscale_err"


echo "$maxscale_err" | grep "$mariadb_err"
if [ "$?" != 0 ] ; then
	echo "Messages are different!"
	exit 1
else
	echo "Messages are same"
	exit 0
fi
