#!/bin/bash

for fail_command in "fail backendfd" "fail clientfd"
do

echo "fail commnd: $fail_command"
ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 \"$fail_command\""
if [ $? != 0 ] ; then 
	echo "$fail_command Failed"
	exit 1
fi
ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4006 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then      
	echo "RWSplit failed"
#        exit 1
fi

ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4006 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then      
	echo "RWSplit failed"
        exit 1
fi

ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 \"$fail_command\""
if [ $? != 0 ] ; then
	echo "$fail_command Failed"
        exit 1
fi
ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4008 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then
	echo "ReadConn failed"
        exit 1
fi

ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4008 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then
        echo "ReadConn failed"
        exit 1
fi

ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "$maxdir/bin/maxadmin -pskysql -uadmin -P6603 \"$fail_command\""
if [ $? != 0 ] ; then
	echo "$fail_command Failed"
        exit 1
fi
ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4009 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then
        echo "ReadConn failed"
        exit 1
fi

ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "echo \"show databases;\" | mysql -h 127.0.0.1 -P 4009 -u$repl_User -p$repl_Password -c"
if [ $? != 0 ] ; then
        echo "ReadConn failed"
        exit 1
fi

done

