#!/bin/bash

export Test_name=bug567
$test_dir/configure_maxscale.sh

pid=`ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "cat $maxdir/log/maxscale.pid"`
echo "Maxscale pid is $pid"
echo "removing log directory from /dev/shm/"
ssh -i $Maxscale_sshkey -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$Maxscale_IP "rm -rf /dev/shm/$pid"
sleep 1
echo "checking if Maxscale is alive"
echo "show databases;" | mysql -u$repl_User -p$repl_Password -h $Maxscale_IP -P 4006 


res=$?

$test_dir/copy_logs.sh bug567
exit $res

