#Checks for all the C system headers found in all the files

  include(CheckFunctionExists)
  include(CheckIncludeFiles)

  check_include_files(arpa/inet.h HAVE_ARPA_INET)
  check_include_files(crypt.h HAVE_CRYPT)
  check_include_files(ctype.h HAVE_CTYPE)
  check_include_files(dirent.h HAVE_DIRENT)
  check_include_files(dlfcn.h HAVE_DLFCN)
  check_include_files(errno.h HAVE_ERRNO)
  check_include_files(execinfo.h HAVE_EXECINFO)
  check_include_files(fcntl.h HAVE_FCNTL)
  check_include_files(ftw.h HAVE_FTW)
  check_include_files(getopt.h HAVE_GETOPT)
  check_include_files(ini.h HAVE_INI)
  check_include_files(math.h HAVE_MATH)
  check_include_files(memlog.h HAVE_MEMLOG)
  check_include_files(netdb.h HAVE_NETDB)
  check_include_files(netinet/in.h HAVE_NETINET_IN)
  check_include_files(openssl/aes.h HAVE_OPENSSL_AES)
  check_include_files(openssl/sha.h HAVE_OPENSSL_SHA)
  check_include_files(pthread.h HAVE_PTHREAD)
  check_include_files(pwd.h HAVE_PWD)
  check_include_files(rdtsc.h HAVE_RDTSC)
  check_include_files(regex.h HAVE_REGEX)
  check_include_files(signal.h HAVE_SIGNAL)
  check_include_files(stdarg.h HAVE_STDARG)
  check_include_files(stdbool.h HAVE_STDBOOL)
  check_include_files(stdint.h HAVE_STDINT)
  check_include_files(stdio.h HAVE_STDIO)
  check_include_files(stdlib.h HAVE_STDLIB)
  check_include_files(string.h HAVE_STRING)
  check_include_files(strings.h HAVE_STRINGS)
  check_include_files(sys/epoll.h HAVE_SYS_EPOLL)
  check_include_files(sys/ioctl.h HAVE_SYS_IOCTL)
  check_include_files(syslog.h HAVE_SYSLOG)
  check_include_files(sys/param.h HAVE_SYS_PARAM)
  check_include_files(sys/socket.h HAVE_SYS_SOCKET)
  check_include_files(sys/stat.h HAVE_SYS_STAT)
  check_include_files(sys/time.h HAVE_SYS_TIME)
  check_include_files(sys/types.h HAVE_SYS_TYPES)
  check_include_files(sys/un.h HAVE_SYS_UN)
  check_include_files(time.h HAVE_TIME)
  check_include_files(unistd.h HAVE_UNISTD)
