#!/bin/bash

$test_dir/configure_maxscale.sh &
sleep 15

export Master_id=`echo "SELECT (@@server_id)" | mysql -u$galera_User -p$galera_Password -h $galera_000 | tail -n1`
$test_dir/Hartmut_tests/mariadb_tests_hartmut_imp 4006

ssh -i $Maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$Maxscale_IP "cat /home/ec2-user/maxscale-mysqltest/fail.txt" | grep "FAILED"
res=$?

$test_dir/copy_logs.sh
exit $res
