#!/bin/bash

scp -i $Maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r /usr/local/skysql/maxscale/system-test/test_ctrl_c/* root@$Maxscale_IP:/home/ec2-user/
ssh -i $Maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$Maxscale_IP '/home/ec2-user/test_ctrl_c.sh'
