#!/bin/bash

#bug 454

$test_dir/configure_maxscale.sh

$test_dir/session_hang/run_setmix.sh &
perl $test_dir/session_hang/simpletest.pl

sleep 15

$test_dir/session_hang/run_setmix.sh &
perl $test_dir/system-test/session_hang/simpletest.pl

sleep 15

$test_dir/session_hang/run_setmix.sh &
perl $test_dir/session_hang/simpletest.pl

sleep 15

$test_dir/system-test/session_hang/run_setmix.sh &
perl $test_dir/system-test/session_hang/simpletest.pl

sleep 15


echo "show databases;" mysql -u$repl_User -p$repl_Password -h$Maxscale_IP -p 4006
