#!/bin/bash

#bug 454

/usr/local/skysql/maxscale/system-test/session_hang/run_setmix.sh &
perl /usr/local/skysql/maxscale/system-test/session_hang/simpletest.pl

sleep 15

/usr/local/skysql/maxscale/system-test/session_hang/run_setmix.sh &
perl /usr/local/skysql/maxscale/system-test/session_hang/simpletest.pl

sleep 15

/usr/local/skysql/maxscale/system-test/session_hang/run_setmix.sh &
perl /usr/local/skysql/maxscale/system-test/session_hang/simpletest.pl

sleep 15

/usr/local/skysql/maxscale/system-test/session_hang/run_setmix.sh &
perl /usr/local/skysql/maxscale/system-test/session_hang/simpletest.pl

sleep 15


echo "show databases;" mysql -u$repl_User -p$repl_Password -h$Maxscale_IP -p 4006
