/*
 * Copyright (c) 2023 MariaDB plc
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file and at www.mariadb.com/bsl11.
 *
 * Change Date: 2029-02-28
 *
 * On the date above, in accordance with the Business Source License, use
 * of this software will be governed by version 2 or later of the General
 * Public License.
 */
import { dateFormat } from '@/utils/helpers'

const SEPARATOR = '# ============================================================================='

export default {
  genHeader: () => {
    const name = 'Generated by MaxScale GUI'
    const time = dateFormat({ value: new Date() })
    return {
      name,
      time,
      content: [SEPARATOR, `# ${name}`, `# ${time}`, SEPARATOR].join('\n'),
    }
  },
  genSection: (name) => `# ${name}\n${SEPARATOR.slice(0, Math.round(SEPARATOR.length / 2))}`,
}
