module.exports = {
    languages: ['mariadb'],
    /**
     * Monaco features
     * Only use necessary features to reduce bundle size,
     */
    // https://github.com/microsoft/monaco-editor-webpack-plugin/blob/main/src/features.ts
    features: [
        '!accessibilityHelp',
        '!anchorSelect',
        '!bracketMatching',
        '!caretOperations',
        'clipboard',
        '!codeAction',
        '!codelens',
        '!colorPicker',
        'comment',
        'contextmenu',
        'coreCommands',
        '!cursorUndo',
        'dnd',
        'documentSymbols',
        'find',
        'folding',
        'fontZoom',
        'format',
        '!gotoError',
        '!gotoLine',
        '!gotoSymbol',
        '!hover',
        '!iPadShowKeyboard',
        '!inPlaceReplace',
        '!indentation',
        '!inlineHints',
        '!inspectTokens',
        '!linesOperations',
        '!linkedEditing',
        '!links',
        'multicursor',
        '!parameterHints',
        'quickCommand',
        '!quickHelp',
        '!quickOutline',
        '!referenceSearch',
        '!rename',
        '!smartSelect',
        '!snippets',
        'suggest',
        '!toggleHighContrast',
        '!toggleTabFocusMode',
        '!transpose',
        '!unusualLineTerminators',
        '!viewportSemanticTokens',
        '!wordHighlighter',
        '!wordOperations',
        '!wordPartOperations',
    ],
}
