[maxscale]
threads=###threads###
log_warning=1

[MySQL Monitor]
type=monitor
module=mysqlmon
servers= server1, server2,server3  ,server4
user=maxskysql
password= skysql
script=/###access_homedir###/script/script.sh --event=$EVENT --initiator=$INITIATOR --nodelist=$NODELIST
events=master_down,master_up, slave_up,   server_down  ,server_up,lost_master,lost_slave,new_master,new_slave
monitor_interval=1000

[Galera Monitor]
type=monitor
module=galeramon
servers=gserver1,gserver2,gserver3,gserver4
script=/###access_homedir###/script/script.sh  --event=$EVENT --initiator=$INITIATOR --nodelist=$NODELIST
events=master_down,master_up, slave_up,   server_down  ,server_up,lost_master,lost_slave,new_master,new_slave,server_down,server_up,synced_down,synced_up
disable_master_role_setting=true
root_node_as_master=false
user=maxskysql
password=skysql
monitor_interval=1000

[RW Split Router]
type=service
router= readwritesplit
servers=server1,     server2,              server3,server4
user=maxskysql
password=skysql
router_options=slave_selection_criteria=LEAST_ROUTER_CONNECTIONS

[RW Split Router Galera]
type=service
router= readwritesplit
servers=gserver1,gserver2,gserver3,gserver4
user=maxskysql
password=skysql
router_options=slave_selection_criteria=LEAST_ROUTER_CONNECTIONS

[Read Connection Router Slave]
type=service
router=readconnroute
router_options= slave
servers=server1,server2,server3,server4
user=maxskysql
password=skysql

[Read Connection Router Master]
type=service
router=readconnroute
router_options=master
servers=server1,server2,server3,server4
user=maxskysql
password=skysql

[RW Split Listener]
type=listener
service=RW Split Router
protocol=MySQLClient
port=4006
#socket=/tmp/rwsplit.sock

[RW Split Listener Galera]
type=listener
service=RW Split Router Galera
protocol=MySQLClient
port=4016
#socket=/tmp/rwsplit.sock

[Read Connection Listener Slave]
type=listener
service=Read Connection Router Slave
protocol=MySQLClient
port=4009

[Read Connection Listener Master]
type=listener
service=Read Connection Router Master
protocol=MySQLClient
port=4008

[CLI]
type=service
router=cli

[CLI Listener]
type=listener
service=CLI
protocol=maxscaled
#address=localhost
socket=default

[server1]
type=server
address=###node_server_IP_1###
port=###node_server_port_1###
protocol=MySQLBackend

[server2]
type=server
address=###node_server_IP_2###
port=###node_server_port_2###
protocol=MySQLBackend

[server3]
type=server
address=###node_server_IP_3###
port=###node_server_port_3###
protocol=MySQLBackend

[server4]
type=server
address=###node_server_IP_4###
port=###node_server_port_4###
protocol=MySQLBackend

[gserver1]
type=server
address=###galera_server_IP_1###
port=###galera_server_port_1###
protocol=MySQLBackend

[gserver2]
type=server
address=###galera_server_IP_2###
port=###galera_server_port_2###
protocol=MySQLBackend

[gserver3]
type=server
address=###galera_server_IP_3###
port=###galera_server_port_3###
protocol=MySQLBackend

[gserver4]
type=server
address=###galera_server_IP_4###
port=###galera_server_port_4###
protocol=MySQLBackend

