#!/bin/bash

port=$1


cat $test_dir/Hartmut_tests/maxscale-mysqltest/r/test_implicit_commit4.result.template | sed "s/####server_id####/$Master_id/" > test_implicit_commit4.result
cat $test_dir/Hartmut_tests/maxscale-mysqltest/r/select_for_var_set.result.template | sed "s/####server_id####/$Master_id/" > select_for_var_set.result

ssh -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$maxscale_IP 'service iptables stop; yum install -y MariaDB-test MariaDB-client; apt-get install -y --force-yes mariadb-test mariadb-client; yum install -y mariadb-test mariadb-client'

scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r $test_dir/Hartmut_tests/maxscale-mysqltest root@$maxscale_IP:/home/ec2-user/
scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r test_implicit_commit4.result root@$maxscale_IP:/home/ec2-user/maxscale-mysqltest/r/
scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r select_for_var_set.result root@$maxscale_IP:/home/ec2-user/maxscale-mysqltest/r/

ssh -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$maxscale_IP "cd /home/ec2-user/maxscale-mysqltest/ ; ls -la ; ./test.sh $port"

