#!/bin/bash

port=$1


cat $test_dir/Hartmut_tests/maxscale-mysqltest/r/test_implicit_commit4.result.template | sed "s/####server_id####/$Master_id/" > test_implicit_commit4.result
cat $test_dir/Hartmut_tests/maxscale-mysqltest/r/select_for_var_set.result.template | sed "s/####server_id####/$Master_id/" > select_for_var_set.result

ssh -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $access_user@$maxscale_IP '$access_sudo service iptables stop; $access_sudo yum install -y MariaDB-test MariaDB-client; $access_sudo apt-get install -y --force-yes mariadb-test mariadb-client; yum install -y mariadb-test mariadb-client'

scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r $test_dir/Hartmut_tests/maxscale-mysqltest $access_user@$maxscale_IP:./
scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r test_implicit_commit4.result $access_user@$maxscale_IP:./maxscale-mysqltest/r/
scp -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -r select_for_var_set.result $access_user@$maxscale_IP:./maxscale-mysqltest/r/

ssh -i $maxscale_sshkey -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $access_user@$maxscale_IP "cd ./maxscale-mysqltest/ ; ls -la ; ./test.sh $port"

