/*
 * Copyright (c) 2023 MariaDB plc
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file and at www.mariadb.com/bsl11.
 *
 * Change Date: 2028-01-30
 *
 * On the date above, in accordance with the Business Source License, use
 * of this software will be governed by version 2 or later of the General
 * Public License.
 */

import { dateFormat } from '@share/utils/helpers'
export default class SqlCommenter {
    block() {
        return '# ============================================================================='
    }
    genHeader() {
        const name = 'Generated by MaxScale GUI'
        const time = dateFormat({ value: new Date() })
        return {
            name,
            time,
            content: [this.block(), `# ${name}`, `# ${time}`, this.block()].join('\n'),
        }
    }
    genSection(name) {
        return `# ${name}\n${this.block().slice(0, Math.round(this.block().length / 2))}`
    }
}
