# cleantests 	- clean local and subdirectories' tests
# buildtests	- build all local and subdirectories' tests
# runtests	- run all local tests 
# testall	- clean, build and run local and subdirectories' tests

include ../../../build_gateway.inc
include ../../../makefile.inc

CC=cc
DEBUG=Y
cleantests:
	- $(DEL) *.o 
	- $(DEL) test_mysql_users
	- $(DEL) *~

testall: cleantests buildtests runtests

buildtests : 
	$(CC) $(CFLAGS) \
	-I$(ROOT_PATH)/server/include \
	-I$(ROOT_PATH)/utils \
	-I$(ROOT_PATH)/log_manager \
	test_mysql_users.c ../secrets.o ../service.o ../gwbitmask.o ../load_utils.o ../session.o ../poll.o ../dcb.o ../utils.o ../buffer.o ../gw_utils.o ../hashtable.o ../atomic.o ../spinlock.o ../users.o ../dbusers.o ../../../utils/skygw_utils.o ../../../log_manager/log_manager.o -o test_mysql_users -L$(EMBEDDED_LIB) -lmysqlclient -lpthread -lssl -lz -lm -lcrypt -lcrypto -ldl -laio -lrt -lstdc++
runtests: 
	@echo ""		
	@echo "-------------------------------"
	@echo $(shell date)			
	@echo "Test MaxScale core"		
	@echo "-------------------------------"
	@echo ""			
	@echo "MaxSclale Load MySQL users"
	@./test_mysql_users
