.TH maxscale 1
.SH NAME
maxscale - An intelligent database proxy
.SH DESCRIPTION
MariaDB MaxScale is an intelligent database proxy that allows the forwarding
of database statements to one or more database servers using complex rules, a
semantic understanding of the database statements and the roles of the various
servers within the backend cluster of databases.

MariaDB MaxScale is designed to provide load balancing and high availability
functionality transparently to the applications. In addition it provides
a highly scalable and flexible architecture, with plugin components to
support different protocols and routing decisions.

Quickstart Guide:

.RS
.I https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale-22-setting-up-mariadb-maxscale/
.RE

Installation Guide:

.RS
.I https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale-22-mariadb-maxscale-installation-guide/
.RE

MaxScale Documentation:

.RS
.I https://mariadb.com/kb/en/mariadb-enterprise/mariadb-maxscale-22-contents/
.RE

.SH BUGS
You can see a list of known bugs and report new bugs at:

.RS
.I https://jira.mariadb.org/browse/MXS
.RE
